#!/usr/bin/env bash
set -euo pipefail

RECORD_DIR="records/track_10min_16mb/2026-03-20_10L_Int5MLP_MuonWD04_SWA50"
ENV_TEMPLATE="${1:-$RECORD_DIR/.env.cloud8gpu_proxy_control}"
TRAIN_SCRIPT="$RECORD_DIR/train_gpt.py"
NPROC="${NPROC_PER_NODE:-8}"

if [[ ! -f "$ENV_TEMPLATE" ]]; then
  echo "missing env template: $ENV_TEMPLATE" >&2
  exit 1
fi

python - <<'PY'
import sentencepiece, torch
print("sentencepiece ok")
print("torch", torch.__version__)
print("cuda", torch.version.cuda)
print("gpus", torch.cuda.device_count())
PY

python - <<'PY'
import importlib.util
print("zstandard", "ok" if importlib.util.find_spec("zstandard") else "missing")
PY

cp "$ENV_TEMPLATE" "$RECORD_DIR/.env"
rm -f train.log

unset RUN_ID LOG_FILE DATA_PATH TOKENIZER_PATH VOCAB_SIZE MAX_WALLCLOCK_SECONDS WARMUP_STEPS
unset TRAIN_LOG_EVERY VAL_LOSS_EVERY TRAIN_BATCH_TOKENS TRAIN_SEQ_LEN NUM_LAYERS BIGRAM_VOCAB_SIZE BIGRAM_DIM BIGRAM_SCALE_INIT
unset EVAL_STRIDE EVAL_BATCH_SEQS COMPILE_MODEL COMPILE_FULLGRAPH COMPILE_DYNAMIC COMPILE_MUON_BACKEND
unset ATTN_BACKEND OPTIMIZER_KIND MLP_KIND SWIGLU_HIDDEN_MULT ATTN_QK_SOFTCAP QK_GAIN_INIT XSA_LAST_N EMA_ENABLED EMA_DECAY ROPE_DIMS LN_SCALE
unset SKIP_WEIGHTS_INIT SMEAR_GATE_INIT ATTN_SCALE_INIT MLP_SCALE_INIT RESID_MIX_X_INIT RESID_MIX_X0_INIT
unset SWA_ENABLED SWA_START_FRAC SWA_EVERY STAGED_DEPTH_ENABLED STAGED_DEPTH_EARLY_LAYERS
unset STAGED_DEPTH_SWITCH_FRAC STAGED_DEPTH_RAMP_STEPS LATE_LAYER_RAMP_ENABLED LATE_LAYER_RAMP_LAYERS
unset LATE_LAYER_RAMP_INIT NORMUON_BETA2 NORMUON_EPS MUON_MOMENTUM MUON_BACKEND_STEPS
unset MUON_MOMENTUM_WARMUP_START MUON_MOMENTUM_WARMUP_STEPS LOG_FIRST_N_STEPS LOG_OPTIMIZER_STEP_MS
unset LOG_STARTUP_TIMES LOG_PHASE_TIMINGS

export LOG_FIRST_N_STEPS="${LOG_FIRST_N_STEPS:-20}"
export LOG_OPTIMIZER_STEP_MS="${LOG_OPTIMIZER_STEP_MS:-1}"
export LOG_STARTUP_TIMES="${LOG_STARTUP_TIMES:-1}"
export LOG_PHASE_TIMINGS="${LOG_PHASE_TIMINGS:-0}"

echo "Using proxy env template: $ENV_TEMPLATE"
grep -E '^(RUN_ID|MAX_WALLCLOCK_SECONDS|WARMUP_STEPS|TRAIN_LOG_EVERY|VAL_LOSS_EVERY|TRAIN_BATCH_TOKENS|TRAIN_SEQ_LEN|NUM_LAYERS|BIGRAM_VOCAB_SIZE|ATTN_BACKEND|OPTIMIZER_KIND|MLP_KIND|XSA_LAST_N|EMA_ENABLED|EMA_DECAY|ROPE_DIMS|LN_SCALE)=' "$RECORD_DIR/.env" || true

torchrun --standalone --nproc_per_node="$NPROC" "$TRAIN_SCRIPT"
